name = "goodpluck"
type = "webpack"
account_id = "b8cd4cd6c22746871556c8214a712815"
zone_id = "8c1bebe51808c902a4fe76fc18397f3f"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.staging]
route = "https://staging.goodpluck.com/*"

[env.production]
routes = ["https://goodpluck.com/*", "https://www.goodpluck.com/*"]
