name = "goodpluck"
main = "workers-site/index.js"
compatibility_date = "2024-09-01"

[site]
bucket = "./public"

[env.staging]
route = "https://staging.goodpluck.com/*"

[env.production]
route = "https://goodpluck.com/*"
