import { VALID_ZIP_PATTERN } from "./util"

// ZIP_CODE_TO_INFO
const ZIP_CODE_TO_INFO = {
  "48001": { city: "Algonac", county: "Saint Clair" },
  "48002": { city: "Allenton", county: "Saint Clair" },
  "48003": { city: "Almont", county: "Lapeer" },
  "48004": { city: "Anchorville", county: "Saint Clair" },
  "48005": { city: "Armada", county: "Macomb" },
  "48006": { city: "Avoca", county: "Saint Clair" },
  "48007": { city: "Troy", county: "Oakland" },
  "48009": { city: "Birmingham", county: "Oakland" },
  "48012": { city: "Birmingham", county: "Oakland" },
  "48014": { city: "Capac", county: "Saint Clair" },
  "48015": { city: "Center Line", county: "Macomb" },
  "48017": { city: "Clawson", county: "Oakland" },
  "48021": { city: "Eastpointe", county: "Macomb" },
  "48022": { city: "Emmett", county: "Saint Clair" },
  "48023": { city: "Fair Haven", county: "Saint Clair" },
  "48025": { city: "Franklin", county: "Oakland" },
  "48026": { city: "Fraser", county: "Macomb" },
  "48027": { city: "Goodells", county: "Saint Clair" },
  "48028": { city: "Harsens Island", county: "Saint Clair" },
  "48030": { city: "Hazel Park", county: "Oakland" },
  "48032": { city: "Jeddo", county: "Saint Clair" },
  "48033": { city: "Southfield", county: "Oakland" },
  "48034": { city: "Southfield", county: "Oakland" },
  "48035": { city: "Clinton Township", county: "Macomb" },
  "48036": { city: "Clinton Township", county: "Macomb" },
  "48037": { city: "Southfield", county: "Oakland" },
  "48038": { city: "Clinton Township", county: "Macomb" },
  "48039": { city: "Marine City", county: "Saint Clair" },
  "48040": { city: "Marysville", county: "Saint Clair" },
  "48041": { city: "Memphis", county: "Saint Clair" },
  "48042": { city: "Macomb", county: "Macomb" },
  "48043": { city: "Mount Clemens", county: "Macomb" },
  "48044": { city: "Macomb", county: "Macomb" },
  "48045": { city: "Harrison Township", county: "Macomb" },
  "48046": { city: "Mount Clemens", county: "Macomb" },
  "48047": { city: "New Baltimore", county: "Macomb" },
  "48048": { city: "New Haven", county: "Macomb" },
  "48049": { city: "North Street", county: "Saint Clair" },
  "48050": { city: "New Haven", county: "Macomb" },
  "48051": { city: "New Baltimore", county: "Macomb" },
  "48054": { city: "East China", county: "Saint Clair" },
  "48059": { city: "Fort Gratiot", county: "Saint Clair" },
  "48060": { city: "Port Huron", county: "Saint Clair" },
  "48061": { city: "Port Huron", county: "Saint Clair" },
  "48062": { city: "Richmond", county: "Macomb" },
  "48063": { city: "Columbus", county: "Saint Clair" },
  "48064": { city: "Casco", county: "Saint Clair" },
  "48065": { city: "Romeo", county: "Macomb" },
  "48066": { city: "Roseville", county: "Macomb" },
  "48067": { city: "Royal Oak", county: "Oakland" },
  "48068": { city: "Royal Oak", county: "Oakland" },
  "48069": { city: "Pleasant Ridge", county: "Oakland" },
  "48070": { city: "Huntington Woods", county: "Oakland" },
  "48071": { city: "Madison Heights", county: "Oakland" },
  "48072": { city: "Berkley", county: "Oakland" },
  "48073": { city: "Royal Oak", county: "Oakland" },
  "48074": { city: "Smiths Creek", county: "Saint Clair" },
  "48075": { city: "Southfield", county: "Oakland" },
  "48076": { city: "Southfield", county: "Oakland" },
  "48079": { city: "Saint Clair", county: "Saint Clair" },
  "48080": { city: "Saint Clair Shores", county: "Macomb" },
  "48081": { city: "Saint Clair Shores", county: "Macomb" },
  "48082": { city: "Saint Clair Shores", county: "Macomb" },
  "48083": { city: "Troy", county: "Oakland" },
  "48084": { city: "Troy", county: "Oakland" },
  "48085": { city: "Troy", county: "Oakland" },
  "48086": { city: "Southfield", county: "Oakland" },
  "48088": { city: "Warren", county: "Macomb" },
  "48089": { city: "Warren", county: "Macomb" },
  "48090": { city: "Warren", county: "Macomb" },
  "48091": { city: "Warren", county: "Macomb" },
  "48092": { city: "Warren", county: "Macomb" },
  "48093": { city: "Warren", county: "Macomb" },
  "48094": { city: "Washington", county: "Macomb" },
  "48095": { city: "Washington", county: "Macomb" },
  "48096": { city: "Ray", county: "Macomb" },
  "48097": { city: "Yale", county: "Saint Clair" },
  "48098": { city: "Troy", county: "Oakland" },
  "48099": { city: "Troy", county: "Oakland" },
  "48101": { city: "Allen Park", county: "Wayne" },
  "48103": { city: "Ann Arbor", county: "Washtenaw" },
  "48104": { city: "Ann Arbor", county: "Washtenaw" },
  "48105": { city: "Ann Arbor", county: "Washtenaw" },
  "48106": { city: "Ann Arbor", county: "Washtenaw" },
  "48107": { city: "Ann Arbor", county: "Washtenaw" },
  "48108": { city: "Ann Arbor", county: "Washtenaw" },
  "48109": { city: "Ann Arbor", county: "Washtenaw" },
  "48110": { city: "Azalia", county: "Monroe" },
  "48111": { city: "Belleville", county: "Wayne" },
  "48112": { city: "Belleville", county: "Wayne" },
  "48113": { city: "Ann Arbor", county: "Washtenaw" },
  "48114": { city: "Brighton", county: "Livingston" },
  "48115": { city: "Bridgewater", county: "Washtenaw" },
  "48116": { city: "Brighton", county: "Livingston" },
  "48117": { city: "Carleton", county: "Monroe" },
  "48118": { city: "Chelsea", county: "Washtenaw" },
  "48120": { city: "Dearborn", county: "Wayne" },
  "48121": { city: "Dearborn", county: "Wayne" },
  "48122": { city: "Melvindale", county: "Wayne" },
  "48123": { city: "Dearborn", county: "Wayne" },
  "48124": { city: "Dearborn", county: "Wayne" },
  "48125": { city: "Dearborn Heights", county: "Wayne" },
  "48126": { city: "Dearborn", county: "Wayne" },
  "48127": { city: "Dearborn Heights", county: "Wayne" },
  "48128": { city: "Dearborn", county: "Wayne" },
  "48130": { city: "Dexter", county: "Washtenaw" },
  "48131": { city: "Dundee", county: "Monroe" },
  "48133": { city: "Erie", county: "Monroe" },
  "48134": { city: "Flat Rock", county: "Wayne" },
  "48135": { city: "Garden City", county: "Wayne" },
  "48136": { city: "Garden City", county: "Wayne" },
  "48137": { city: "Gregory", county: "Livingston" },
  "48138": { city: "Grosse Ile", county: "Wayne" },
  "48139": { city: "Hamburg", county: "Livingston" },
  "48140": { city: "Ida", county: "Monroe" },
  "48141": { city: "Inkster", county: "Wayne" },
  "48143": { city: "Lakeland", county: "Livingston" },
  "48144": { city: "Lambertville", county: "Monroe" },
  "48145": { city: "La Salle", county: "Monroe" },
  "48146": { city: "Lincoln Park", county: "Wayne" },
  "48150": { city: "Livonia", county: "Wayne" },
  "48151": { city: "Livonia", county: "Wayne" },
  "48152": { city: "Livonia", county: "Wayne" },
  "48153": { city: "Livonia", county: "Wayne" },
  "48154": { city: "Livonia", county: "Wayne" },
  "48157": { city: "Luna Pier", county: "Monroe" },
  "48158": { city: "Manchester", county: "Washtenaw" },
  "48159": { city: "Maybee", county: "Monroe" },
  "48160": { city: "Milan", county: "Monroe" },
  "48161": { city: "Monroe", county: "Monroe" },
  "48162": { city: "Monroe", county: "Monroe" },
  "48164": { city: "New Boston", county: "Wayne" },
  "48165": { city: "New Hudson", county: "Oakland" },
  "48166": { city: "Newport", county: "Monroe" },
  "48167": { city: "Northville", county: "Wayne" },
  "48168": { city: "Northville", county: "Wayne" },
  "48169": { city: "Pinckney", county: "Livingston" },
  "48170": { city: "Plymouth", county: "Wayne" },
  "48173": { city: "Rockwood", county: "Wayne" },
  "48174": { city: "Romulus", county: "Wayne" },
  "48175": { city: "Salem", county: "Washtenaw" },
  "48176": { city: "Saline", county: "Washtenaw" },
  "48177": { city: "Samaria", county: "Monroe" },
  "48178": { city: "South Lyon", county: "Oakland" },
  "48179": { city: "South Rockwood", county: "Monroe" },
  "48180": { city: "Taylor", county: "Wayne" },
  "48182": { city: "Temperance", county: "Monroe" },
  "48183": { city: "Trenton", county: "Wayne" },
  "48184": { city: "Wayne", county: "Wayne" },
  "48185": { city: "Westland", county: "Wayne" },
  "48186": { city: "Westland", county: "Wayne" },
  "48187": { city: "Canton", county: "Wayne" },
  "48188": { city: "Canton", county: "Wayne" },
  "48189": { city: "Whitmore Lake", county: "Washtenaw" },
  "48190": { city: "Whittaker", county: "Washtenaw" },
  "48191": { city: "Willis", county: "Washtenaw" },
  "48192": { city: "Wyandotte", county: "Wayne" },
  "48193": { city: "Riverview", county: "Wayne" },
  "48195": { city: "Southgate", county: "Wayne" },
  "48197": { city: "Ypsilanti", county: "Washtenaw" },
  "48198": { city: "Ypsilanti", county: "Washtenaw" },
  "48201": { city: "Detroit", county: "Wayne" },
  "48202": { city: "Detroit", county: "Wayne" },
  "48203": { city: "Highland Park", county: "Wayne" },
  "48204": { city: "Detroit", county: "Wayne" },
  "48205": { city: "Detroit", county: "Wayne" },
  "48206": { city: "Detroit", county: "Wayne" },
  "48207": { city: "Detroit", county: "Wayne" },
  "48208": { city: "Detroit", county: "Wayne" },
  "48209": { city: "Detroit", county: "Wayne" },
  "48210": { city: "Detroit", county: "Wayne" },
  "48211": { city: "Detroit", county: "Wayne" },
  "48212": { city: "Hamtramck", county: "Wayne" },
  "48213": { city: "Detroit", county: "Wayne" },
  "48214": { city: "Detroit", county: "Wayne" },
  "48215": { city: "Detroit", county: "Wayne" },
  "48216": { city: "Detroit", county: "Wayne" },
  "48217": { city: "Detroit", county: "Wayne" },
  "48218": { city: "River Rouge", county: "Wayne" },
  "48219": { city: "Detroit", county: "Wayne" },
  "48220": { city: "Ferndale", county: "Oakland" },
  "48221": { city: "Detroit", county: "Wayne" },
  "48222": { city: "Detroit", county: "Wayne" },
  "48223": { city: "Detroit", county: "Wayne" },
  "48224": { city: "Detroit", county: "Wayne" },
  "48225": { city: "Harper Woods", county: "Wayne" },
  "48226": { city: "Detroit", county: "Wayne" },
  "48227": { city: "Detroit", county: "Wayne" },
  "48228": { city: "Detroit", county: "Wayne" },
  "48229": { city: "Ecorse", county: "Wayne" },
  "48230": { city: "Grosse Pointe", county: "Wayne" },
  "48231": { city: "Detroit", county: "Wayne" },
  "48232": { city: "Detroit", county: "Wayne" },
  "48233": { city: "Detroit", county: "Wayne" },
  "48234": { city: "Detroit", county: "Wayne" },
  "48235": { city: "Detroit", county: "Wayne" },
  "48236": { city: "Grosse Pointe", county: "Wayne" },
  "48237": { city: "Oak Park", county: "Oakland" },
  "48238": { city: "Detroit", county: "Wayne" },
  "48239": { city: "Redford", county: "Wayne" },
  "48240": { city: "Redford", county: "Wayne" },
  "48242": { city: "Detroit", county: "Wayne" },
  "48243": { city: "Detroit", county: "Wayne" },
  "48244": { city: "Detroit", county: "Wayne" },
  "48255": { city: "Detroit", county: "Wayne" },
  "48260": { city: "Detroit", county: "Wayne" },
  "48264": { city: "Detroit", county: "Wayne" },
  "48265": { city: "Detroit", county: "Wayne" },
  "48266": { city: "Detroit", county: "Wayne" },
  "48267": { city: "Detroit", county: "Wayne" },
  "48268": { city: "Detroit", county: "Wayne" },
  "48269": { city: "Detroit", county: "Wayne" },
  "48272": { city: "Detroit", county: "Wayne" },
  "48275": { city: "Detroit", county: "Wayne" },
  "48277": { city: "Detroit", county: "Wayne" },
  "48278": { city: "Detroit", county: "Wayne" },
  "48279": { city: "Detroit", county: "Wayne" },
  "48288": { city: "Detroit", county: "Wayne" },
  "48301": { city: "Bloomfield Hills", county: "Oakland" },
  "48302": { city: "Bloomfield Hills", county: "Oakland" },
  "48303": { city: "Bloomfield Hills", county: "Oakland" },
  "48304": { city: "Bloomfield Hills", county: "Oakland" },
  "48306": { city: "Rochester", county: "Oakland" },
  "48307": { city: "Rochester", county: "Oakland" },
  "48308": { city: "Rochester", county: "Oakland" },
  "48309": { city: "Rochester", county: "Oakland" },
  "48310": { city: "Sterling Heights", county: "Macomb" },
  "48311": { city: "Sterling Heights", county: "Macomb" },
  "48312": { city: "Sterling Heights", county: "Macomb" },
  "48313": { city: "Sterling Heights", county: "Macomb" },
  "48314": { city: "Sterling Heights", county: "Macomb" },
  "48315": { city: "Utica", county: "Macomb" },
  "48316": { city: "Utica", county: "Macomb" },
  "48317": { city: "Utica", county: "Macomb" },
  "48318": { city: "Utica", county: "Macomb" },
  "48320": { city: "Keego Harbor", county: "Oakland" },
  "48321": { city: "Auburn Hills", county: "Oakland" },
  "48322": { city: "West Bloomfield", county: "Oakland" },
  "48323": { city: "West Bloomfield", county: "Oakland" },
  "48324": { city: "West Bloomfield", county: "Oakland" },
  "48325": { city: "West Bloomfield", county: "Oakland" },
  "48326": { city: "Auburn Hills", county: "Oakland" },
  "48327": { city: "Waterford", county: "Oakland" },
  "48328": { city: "Waterford", county: "Oakland" },
  "48329": { city: "Waterford", county: "Oakland" },
  "48330": { city: "Drayton Plains", county: "Oakland" },
  "48331": { city: "Farmington", county: "Oakland" },
  "48332": { city: "Farmington", county: "Oakland" },
  "48333": { city: "Farmington", county: "Oakland" },
  "48334": { city: "Farmington", county: "Oakland" },
  "48335": { city: "Farmington", county: "Oakland" },
  "48336": { city: "Farmington", county: "Oakland" },
  "48340": { city: "Pontiac", county: "Oakland" },
  "48341": { city: "Pontiac", county: "Oakland" },
  "48342": { city: "Pontiac", county: "Oakland" },
  "48343": { city: "Pontiac", county: "Oakland" },
  "48346": { city: "Clarkston", county: "Oakland" },
  "48347": { city: "Clarkston", county: "Oakland" },
  "48348": { city: "Clarkston", county: "Oakland" },
  "48350": { city: "Davisburg", county: "Oakland" },
  "48353": { city: "Hartland", county: "Livingston" },
  "48356": { city: "Highland", county: "Oakland" },
  "48357": { city: "Highland", county: "Oakland" },
  "48359": { city: "Lake Orion", county: "Oakland" },
  "48360": { city: "Lake Orion", county: "Oakland" },
  "48361": { city: "Lake Orion", county: "Oakland" },
  "48362": { city: "Lake Orion", county: "Oakland" },
  "48363": { city: "Oakland", county: "Oakland" },
  "48366": { city: "Lakeville", county: "Oakland" },
  "48367": { city: "Leonard", county: "Oakland" },
  "48370": { city: "Oxford", county: "Oakland" },
  "48371": { city: "Oxford", county: "Oakland" },
  "48374": { city: "Novi", county: "Oakland" },
  "48375": { city: "Novi", county: "Oakland" },
  "48376": { city: "Novi", county: "Oakland" },
  "48377": { city: "Novi", county: "Oakland" },
  "48380": { city: "Milford", county: "Oakland" },
  "48381": { city: "Milford", county: "Oakland" },
  "48382": { city: "Commerce Township", county: "Oakland" },
  "48383": { city: "White Lake", county: "Oakland" },
  "48386": { city: "White Lake", county: "Oakland" },
  "48387": { city: "Union Lake", county: "Oakland" },
  "48390": { city: "Walled Lake", county: "Oakland" },
  "48391": { city: "Walled Lake", county: "Oakland" },
  "48393": { city: "Wixom", county: "Oakland" },
  "48397": { city: "Warren", county: "Macomb" },
  "48401": { city: "Applegate", county: "Sanilac" },
  "48410": { city: "Argyle", county: "Sanilac" },
  "48411": { city: "Atlas", county: "Genesee" },
  "48412": { city: "Attica", county: "Lapeer" },
  "48413": { city: "Bad Axe", county: "Huron" },
  "48414": { city: "Bancroft", county: "Shiawassee" },
  "48415": { city: "Birch Run", county: "Saginaw" },
  "48416": { city: "Brown City", county: "Sanilac" },
  "48417": { city: "Burt", county: "Saginaw" },
  "48418": { city: "Byron", county: "Shiawassee" },
  "48419": { city: "Carsonville", county: "Sanilac" },
  "48420": { city: "Clio", county: "Genesee" },
  "48421": { city: "Columbiaville", county: "Lapeer" },
  "48422": { city: "Croswell", county: "Sanilac" },
  "48423": { city: "Davison", county: "Genesee" },
  "48426": { city: "Decker", county: "Sanilac" },
  "48427": { city: "Deckerville", county: "Sanilac" },
  "48428": { city: "Dryden", county: "Lapeer" },
  "48429": { city: "Durand", county: "Shiawassee" },
  "48430": { city: "Fenton", county: "Genesee" },
  "48432": { city: "Filion", county: "Huron" },
  "48433": { city: "Flushing", county: "Genesee" },
  "48434": { city: "Forestville", county: "Sanilac" },
  "48435": { city: "Fostoria", county: "Tuscola" },
  "48436": { city: "Gaines", county: "Genesee" },
  "48437": { city: "Genesee", county: "Genesee" },
  "48438": { city: "Goodrich", county: "Genesee" },
  "48439": { city: "Grand Blanc", county: "Genesee" },
  "48440": { city: "Hadley", county: "Lapeer" },
  "48441": { city: "Harbor Beach", county: "Huron" },
  "48442": { city: "Holly", county: "Oakland" },
  "48444": { city: "Imlay City", county: "Lapeer" },
  "48445": { city: "Kinde", county: "Huron" },
  "48446": { city: "Lapeer", county: "Lapeer" },
  "48449": { city: "Lennon", county: "Genesee" },
  "48450": { city: "Lexington", county: "Sanilac" },
  "48451": { city: "Linden", county: "Genesee" },
  "48453": { city: "Marlette", county: "Sanilac" },
  "48454": { city: "Melvin", county: "Sanilac" },
  "48455": { city: "Metamora", county: "Lapeer" },
  "48456": { city: "Minden City", county: "Sanilac" },
  "48457": { city: "Montrose", county: "Genesee" },
  "48458": { city: "Mount Morris", county: "Genesee" },
  "48460": { city: "New Lothrop", county: "Shiawassee" },
  "48461": { city: "North Branch", county: "Lapeer" },
  "48462": { city: "Ortonville", county: "Oakland" },
  "48463": { city: "Otisville", county: "Genesee" },
  "48464": { city: "Otter Lake", county: "Lapeer" },
  "48465": { city: "Palms", county: "Sanilac" },
  "48466": { city: "Peck", county: "Sanilac" },
  "48467": { city: "Port Austin", county: "Huron" },
  "48468": { city: "Port Hope", county: "Huron" },
  "48469": { city: "Port Sanilac", county: "Sanilac" },
  "48470": { city: "Ruth", county: "Huron" },
  "48471": { city: "Sandusky", county: "Sanilac" },
  "48472": { city: "Snover", county: "Sanilac" },
  "48473": { city: "Swartz Creek", county: "Genesee" },
  "48475": { city: "Ubly", county: "Huron" },
  "48476": { city: "Vernon", county: "Shiawassee" },
  "48480": { city: "Grand Blanc", county: "Genesee" },
  "48501": { city: "Flint", county: "Genesee" },
  "48502": { city: "Flint", county: "Genesee" },
  "48503": { city: "Flint", county: "Genesee" },
  "48504": { city: "Flint", county: "Genesee" },
  "48505": { city: "Flint", county: "Genesee" },
  "48506": { city: "Flint", county: "Genesee" },
  "48507": { city: "Flint", county: "Genesee" },
  "48509": { city: "Burton", county: "Genesee" },
  "48519": { city: "Burton", county: "Genesee" },
  "48529": { city: "Burton", county: "Genesee" },
  "48531": { city: "Flint", county: "Genesee" },
  "48532": { city: "Flint", county: "Genesee" },
  "48550": { city: "Flint", county: "Genesee" },
  "48551": { city: "Flint", county: "Genesee" },
  "48552": { city: "Flint", county: "Genesee" },
  "48553": { city: "Flint", county: "Genesee" },
  "48554": { city: "Flint", county: "Genesee" },
  "48555": { city: "Flint", county: "Genesee" },
  "48556": { city: "Flint", county: "Genesee" },
  "48557": { city: "Flint", county: "Genesee" },
  "48559": { city: "Flint", county: "Genesee" },
  "48601": { city: "Saginaw", county: "Saginaw" },
  "48602": { city: "Saginaw", county: "Saginaw" },
  "48603": { city: "Saginaw", county: "Saginaw" },
  "48604": { city: "Saginaw", county: "Saginaw" },
  "48605": { city: "Saginaw", county: "Saginaw" },
  "48606": { city: "Saginaw", county: "Saginaw" },
  "48607": { city: "Saginaw", county: "Saginaw" },
  "48608": { city: "Saginaw", county: "Saginaw" },
  "48609": { city: "Saginaw", county: "Saginaw" },
  "48610": { city: "Alger", county: "Arenac" },
  "48611": { city: "Auburn", county: "Bay" },
  "48612": { city: "Beaverton", county: "Gladwin" },
  "48613": { city: "Bentley", county: "Bay" },
  "48614": { city: "Brant", county: "Saginaw" },
  "48615": { city: "Breckenridge", county: "Gratiot" },
  "48616": { city: "Chesaning", county: "Saginaw" },
  "48617": { city: "Clare", county: "Clare" },
  "48618": { city: "Coleman", county: "Midland" },
  "48619": { city: "Comins", county: "Oscoda" },
  "48620": { city: "Edenville", county: "Midland" },
  "48621": { city: "Fairview", county: "Oscoda" },
  "48622": { city: "Farwell", county: "Clare" },
  "48623": { city: "Freeland", county: "Saginaw" },
  "48624": { city: "Gladwin", county: "Gladwin" },
  "48625": { city: "Harrison", county: "Clare" },
  "48626": { city: "Hemlock", county: "Saginaw" },
  "48627": { city: "Higgins Lake", county: "Roscommon" },
  "48628": { city: "Hope", county: "Midland" },
  "48629": { city: "Houghton Lake", county: "Roscommon" },
  "48630": { city: "Houghton Lake Heights", county: "Roscommon" },
  "48631": { city: "Kawkawlin", county: "Bay" },
  "48632": { city: "Lake", county: "Clare" },
  "48633": { city: "Lake George", county: "Clare" },
  "48634": { city: "Linwood", county: "Bay" },
  "48635": { city: "Lupton", county: "Ogemaw" },
  "48636": { city: "Luzerne", county: "Oscoda" },
  "48637": { city: "Merrill", county: "Saginaw" },
  "48638": { city: "Saginaw", county: "Saginaw" },
  "48640": { city: "Midland", county: "Midland" },
  "48641": { city: "Midland", county: "Midland" },
  "48642": { city: "Midland", county: "Midland" },
  "48647": { city: "Mio", county: "Oscoda" },
  "48649": { city: "Oakley", county: "Saginaw" },
  "48650": { city: "Pinconning", county: "Bay" },
  "48651": { city: "Prudenville", county: "Roscommon" },
  "48652": { city: "Rhodes", county: "Gladwin" },
  "48653": { city: "Roscommon", county: "Roscommon" },
  "48654": { city: "Rose City", county: "Ogemaw" },
  "48655": { city: "Saint Charles", county: "Saginaw" },
  "48656": { city: "Saint Helen", county: "Roscommon" },
  "48657": { city: "Sanford", county: "Midland" },
  "48658": { city: "Standish", county: "Arenac" },
  "48659": { city: "Sterling", county: "Arenac" },
  "48661": { city: "West Branch", county: "Ogemaw" },
  "48662": { city: "Wheeler", county: "Gratiot" },
  "48663": { city: "Saginaw", county: "Saginaw" },
  "48667": { city: "Midland", county: "Midland" },
  "48670": { city: "Midland", county: "Midland" },
  "48674": { city: "Midland", county: "Midland" },
  "48686": { city: "Midland", county: "Midland" },
  "48701": { city: "Akron", county: "Tuscola" },
  "48703": { city: "Au Gres", county: "Arenac" },
  "48705": { city: "Barton City", county: "Alcona" },
  "48706": { city: "Bay City", county: "Bay" },
  "48707": { city: "Bay City", county: "Bay" },
  "48708": { city: "Bay City", county: "Bay" },
  "48710": { city: "University Center", county: "Bay" },
  "48720": { city: "Bay Port", county: "Huron" },
  "48721": { city: "Black River", county: "Alcona" },
  "48722": { city: "Bridgeport", county: "Saginaw" },
  "48723": { city: "Caro", county: "Tuscola" },
  "48724": { city: "Carrollton", county: "Saginaw" },
  "48725": { city: "Caseville", county: "Huron" },
  "48726": { city: "Cass City", county: "Tuscola" },
  "48727": { city: "Clifford", county: "Lapeer" },
  "48728": { city: "Curran", county: "Alcona" },
  "48729": { city: "Deford", county: "Tuscola" },
  "48730": { city: "East Tawas", county: "Iosco" },
  "48731": { city: "Elkton", county: "Huron" },
  "48732": { city: "Essexville", county: "Bay" },
  "48733": { city: "Fairgrove", county: "Tuscola" },
  "48734": { city: "Frankenmuth", county: "Saginaw" },
  "48735": { city: "Gagetown", county: "Tuscola" },
  "48736": { city: "Gilford", county: "Tuscola" },
  "48737": { city: "Glennie", county: "Alcona" },
  "48738": { city: "Greenbush", county: "Alcona" },
  "48739": { city: "Hale", county: "Iosco" },
  "48740": { city: "Harrisville", county: "Alcona" },
  "48741": { city: "Kingston", county: "Tuscola" },
  "48742": { city: "Lincoln", county: "Alcona" },
  "48743": { city: "Long Lake", county: "Iosco" },
  "48744": { city: "Mayville", county: "Tuscola" },
  "48745": { city: "Mikado", county: "Alcona" },
  "48746": { city: "Millington", county: "Tuscola" },
  "48747": { city: "Munger", county: "Bay" },
  "48748": { city: "National City", county: "Iosco" },
  "48749": { city: "Omer", county: "Arenac" },
  "48750": { city: "Oscoda", county: "Iosco" },
  "48754": { city: "Owendale", county: "Huron" },
  "48755": { city: "Pigeon", county: "Huron" },
  "48756": { city: "Prescott", county: "Ogemaw" },
  "48757": { city: "Reese", county: "Tuscola" },
  "48758": { city: "Richville", county: "Tuscola" },
  "48759": { city: "Sebewaing", county: "Huron" },
  "48760": { city: "Silverwood", county: "Lapeer" },
  "48761": { city: "South Branch", county: "Ogemaw" },
  "48762": { city: "Spruce", county: "Alcona" },
  "48763": { city: "Tawas City", county: "Iosco" },
  "48764": { city: "Tawas City", county: "Iosco" },
  "48765": { city: "Turner", county: "Arenac" },
  "48766": { city: "Twining", county: "Arenac" },
  "48767": { city: "Unionville", county: "Tuscola" },
  "48768": { city: "Vassar", county: "Tuscola" },
  "48769": { city: "Tuscola", county: "Tuscola" },
  "48770": { city: "Whittemore", county: "Iosco" },
  "48787": { city: "Frankenmuth", county: "Saginaw" },
  "48801": { city: "Alma", county: "Gratiot" },
  "48802": { city: "Alma", county: "Gratiot" },
  "48804": { city: "Mount Pleasant", county: "Isabella" },
  "48805": { city: "Okemos", county: "Ingham" },
  "48806": { city: "Ashley", county: "Gratiot" },
  "48807": { city: "Bannister", county: "Gratiot" },
  "48808": { city: "Bath", county: "Clinton" },
  "48809": { city: "Belding", county: "Ionia" },
  "48811": { city: "Carson City", county: "Montcalm" },
  "48812": { city: "Cedar Lake", county: "Montcalm" },
  "48813": { city: "Charlotte", county: "Eaton" },
  "48815": { city: "Clarksville", county: "Ionia" },
  "48816": { city: "Cohoctah", county: "Livingston" },
  "48817": { city: "Corunna", county: "Shiawassee" },
  "48818": { city: "Crystal", county: "Montcalm" },
  "48819": { city: "Dansville", county: "Ingham" },
  "48820": { city: "Dewitt", county: "Clinton" },
  "48821": { city: "Dimondale", county: "Eaton" },
  "48822": { city: "Eagle", county: "Clinton" },
  "48823": { city: "East Lansing", county: "Ingham" },
  "48824": { city: "East Lansing", county: "Ingham" },
  "48825": { city: "East Lansing", county: "Ingham" },
  "48826": { city: "East Lansing", county: "Ingham" },
  "48827": { city: "Eaton Rapids", county: "Eaton" },
  "48829": { city: "Edmore", county: "Montcalm" },
  "48830": { city: "Elm Hall", county: "Gratiot" },
  "48831": { city: "Elsie", county: "Clinton" },
  "48832": { city: "Elwell", county: "Gratiot" },
  "48833": { city: "Eureka", county: "Clinton" },
  "48834": { city: "Fenwick", county: "Montcalm" },
  "48835": { city: "Fowler", county: "Clinton" },
  "48836": { city: "Fowlerville", county: "Livingston" },
  "48837": { city: "Grand Ledge", county: "Eaton" },
  "48838": { city: "Greenville", county: "Montcalm" },
  "48840": { city: "Haslett", county: "Ingham" },
  "48841": { city: "Henderson", county: "Shiawassee" },
  "48842": { city: "Holt", county: "Ingham" },
  "48843": { city: "Howell", county: "Livingston" },
  "48844": { city: "Howell", county: "Livingston" },
  "48845": { city: "Hubbardston", county: "Ionia" },
  "48846": { city: "Ionia", county: "Ionia" },
  "48847": { city: "Ithaca", county: "Gratiot" },
  "48848": { city: "Laingsburg", county: "Shiawassee" },
  "48849": { city: "Lake Odessa", county: "Ionia" },
  "48850": { city: "Lakeview", county: "Montcalm" },
  "48851": { city: "Lyons", county: "Ionia" },
  "48852": { city: "Mcbrides", county: "Montcalm" },
  "48853": { city: "Maple Rapids", county: "Clinton" },
  "48854": { city: "Mason", county: "Ingham" },
  "48855": { city: "Howell", county: "Livingston" },
  "48856": { city: "Middleton", county: "Gratiot" },
  "48857": { city: "Morrice", county: "Shiawassee" },
  "48858": { city: "Mount Pleasant", county: "Isabella" },
  "48859": { city: "Mount Pleasant", county: "Isabella" },
  "48860": { city: "Muir", county: "Ionia" },
  "48861": { city: "Mulliken", county: "Eaton" },
  "48862": { city: "North Star", county: "Gratiot" },
  "48863": { city: "Oak Grove", county: "Livingston" },
  "48864": { city: "Okemos", county: "Ingham" },
  "48865": { city: "Orleans", county: "Ionia" },
  "48866": { city: "Ovid", county: "Clinton" },
  "48867": { city: "Owosso", county: "Shiawassee" },
  "48870": { city: "Palo", county: "Ionia" },
  "48871": { city: "Perrinton", county: "Gratiot" },
  "48872": { city: "Perry", county: "Shiawassee" },
  "48873": { city: "Pewamo", county: "Ionia" },
  "48874": { city: "Pompeii", county: "Gratiot" },
  "48875": { city: "Portland", county: "Ionia" },
  "48876": { city: "Potterville", county: "Eaton" },
  "48877": { city: "Riverdale", county: "Gratiot" },
  "48878": { city: "Rosebush", county: "Isabella" },
  "48879": { city: "Saint Johns", county: "Clinton" },
  "48880": { city: "Saint Louis", county: "Gratiot" },
  "48881": { city: "Saranac", county: "Ionia" },
  "48882": { city: "Shaftsburg", county: "Shiawassee" },
  "48883": { city: "Shepherd", county: "Isabella" },
  "48884": { city: "Sheridan", county: "Montcalm" },
  "48885": { city: "Sidney", county: "Montcalm" },
  "48886": { city: "Six Lakes", county: "Montcalm" },
  "48887": { city: "Smyrna", county: "Ionia" },
  "48888": { city: "Stanton", county: "Montcalm" },
  "48889": { city: "Sumner", county: "Gratiot" },
  "48890": { city: "Sunfield", county: "Eaton" },
  "48891": { city: "Vestaburg", county: "Montcalm" },
  "48892": { city: "Webberville", county: "Ingham" },
  "48893": { city: "Weidman", county: "Isabella" },
  "48894": { city: "Westphalia", county: "Clinton" },
  "48895": { city: "Williamston", county: "Ingham" },
  "48896": { city: "Winn", county: "Isabella" },
  "48897": { city: "Woodland", county: "Barry" },
  "48901": { city: "Lansing", county: "Ingham" },
  "48906": { city: "Lansing", county: "Ingham" },
  "48908": { city: "Lansing", county: "Eaton" },
  "48909": { city: "Lansing", county: "Ingham" },
  "48910": { city: "Lansing", county: "Ingham" },
  "48911": { city: "Lansing", county: "Ingham" },
  "48912": { city: "Lansing", county: "Ingham" },
  "48913": { city: "Lansing", county: "Ingham" },
  "48915": { city: "Lansing", county: "Ingham" },
  "48916": { city: "Lansing", county: "Ingham" },
  "48917": { city: "Lansing", county: "Eaton" },
  "48918": { city: "Lansing", county: "Ingham" },
  "48919": { city: "Lansing", county: "Ingham" },
  "48921": { city: "Lansing", county: "Ingham" },
  "48922": { city: "Lansing", county: "Ingham" },
  "48924": { city: "Lansing", county: "Ingham" },
  "48929": { city: "Lansing", county: "Ingham" },
  "48930": { city: "Lansing", county: "Ingham" },
  "48933": { city: "Lansing", county: "Ingham" },
  "48937": { city: "Lansing", county: "Ingham" },
  "48950": { city: "Lansing", county: "Ingham" },
  "48951": { city: "Lansing", county: "Ingham" },
  "48956": { city: "Lansing", county: "Ingham" },
  "48980": { city: "Lansing", county: "Ingham" },
  "49001": { city: "Kalamazoo", county: "Kalamazoo" },
  "49002": { city: "Portage", county: "Kalamazoo" },
  "49003": { city: "Kalamazoo", county: "Kalamazoo" },
  "49004": { city: "Kalamazoo", county: "Kalamazoo" },
  "49005": { city: "Kalamazoo", county: "Kalamazoo" },
  "49006": { city: "Kalamazoo", county: "Kalamazoo" },
  "49007": { city: "Kalamazoo", county: "Kalamazoo" },
  "49008": { city: "Kalamazoo", county: "Kalamazoo" },
  "49009": { city: "Kalamazoo", county: "Kalamazoo" },
  "49010": { city: "Allegan", county: "Allegan" },
  "49011": { city: "Athens", county: "Calhoun" },
  "49012": { city: "Augusta", county: "Kalamazoo" },
  "49013": { city: "Bangor", county: "Van Buren" },
  "49014": { city: "Battle Creek", county: "Calhoun" },
  "49015": { city: "Battle Creek", county: "Calhoun" },
  "49016": { city: "Battle Creek", county: "Calhoun" },
  "49017": { city: "Battle Creek", county: "Calhoun" },
  "49018": { city: "Battle Creek", county: "Calhoun" },
  "49019": { city: "Kalamazoo", county: "Kalamazoo" },
  "49020": { city: "Bedford", county: "Calhoun" },
  "49021": { city: "Bellevue", county: "Eaton" },
  "49022": { city: "Benton Harbor", county: "Berrien" },
  "49023": { city: "Benton Harbor", county: "Berrien" },
  "49024": { city: "Portage", county: "Kalamazoo" },
  "49026": { city: "Bloomingdale", county: "Van Buren" },
  "49027": { city: "Breedsville", county: "Van Buren" },
  "49028": { city: "Bronson", county: "Branch" },
  "49029": { city: "Burlington", county: "Calhoun" },
  "49030": { city: "Burr Oak", county: "Saint Joseph" },
  "49031": { city: "Cassopolis", county: "Cass" },
  "49032": { city: "Centreville", county: "Saint Joseph" },
  "49033": { city: "Ceresco", county: "Calhoun" },
  "49034": { city: "Climax", county: "Kalamazoo" },
  "49035": { city: "Cloverdale", county: "Barry" },
  "49036": { city: "Coldwater", county: "Branch" },
  "49038": { city: "Coloma", county: "Berrien" },
  "49039": { city: "Hagar Shores", county: "Berrien" },
  "49040": { city: "Colon", county: "Saint Joseph" },
  "49041": { city: "Comstock", county: "Kalamazoo" },
  "49042": { city: "Constantine", county: "Saint Joseph" },
  "49043": { city: "Covert", county: "Van Buren" },
  "49045": { city: "Decatur", county: "Van Buren" },
  "49046": { city: "Delton", county: "Barry" },
  "49047": { city: "Dowagiac", county: "Cass" },
  "49048": { city: "Kalamazoo", county: "Kalamazoo" },
  "49050": { city: "Dowling", county: "Barry" },
  "49051": { city: "East Leroy", county: "Calhoun" },
  "49052": { city: "Fulton", county: "Kalamazoo" },
  "49053": { city: "Galesburg", county: "Kalamazoo" },
  "49055": { city: "Gobles", county: "Van Buren" },
  "49056": { city: "Grand Junction", county: "Van Buren" },
  "49057": { city: "Hartford", county: "Van Buren" },
  "49058": { city: "Hastings", county: "Barry" },
  "49060": { city: "Hickory Corners", county: "Barry" },
  "49061": { city: "Jones", county: "Cass" },
  "49062": { city: "Kendall", county: "Van Buren" },
  "49063": { city: "Lacota", county: "Van Buren" },
  "49064": { city: "Lawrence", county: "Van Buren" },
  "49065": { city: "Lawton", county: "Van Buren" },
  "49066": { city: "Leonidas", county: "Saint Joseph" },
  "49067": { city: "Marcellus", county: "Cass" },
  "49068": { city: "Marshall", county: "Calhoun" },
  "49069": { city: "Marshall", county: "Calhoun" },
  "49070": { city: "Martin", county: "Allegan" },
  "49071": { city: "Mattawan", county: "Van Buren" },
  "49072": { city: "Mendon", county: "Saint Joseph" },
  "49073": { city: "Nashville", county: "Barry" },
  "49074": { city: "Nazareth", county: "Kalamazoo" },
  "49075": { city: "Nottawa", county: "Saint Joseph" },
  "49076": { city: "Olivet", county: "Eaton" },
  "49077": { city: "Oshtemo", county: "Kalamazoo" },
  "49078": { city: "Otsego", county: "Allegan" },
  "49079": { city: "Paw Paw", county: "Van Buren" },
  "49080": { city: "Plainwell", county: "Allegan" },
  "49081": { city: "Portage", county: "Kalamazoo" },
  "49082": { city: "Quincy", county: "Branch" },
  "49083": { city: "Richland", county: "Kalamazoo" },
  "49084": { city: "Riverside", county: "Berrien" },
  "49085": { city: "Saint Joseph", county: "Berrien" },
  "49087": { city: "Schoolcraft", county: "Kalamazoo" },
  "49088": { city: "Scotts", county: "Kalamazoo" },
  "49089": { city: "Sherwood", county: "Branch" },
  "49090": { city: "South Haven", county: "Van Buren" },
  "49091": { city: "Sturgis", county: "Saint Joseph" },
  "49092": { city: "Tekonsha", county: "Calhoun" },
  "49093": { city: "Three Rivers", county: "Saint Joseph" },
  "49094": { city: "Union City", county: "Branch" },
  "49095": { city: "Vandalia", county: "Cass" },
  "49096": { city: "Vermontville", county: "Eaton" },
  "49097": { city: "Vicksburg", county: "Kalamazoo" },
  "49098": { city: "Watervliet", county: "Berrien" },
  "49099": { city: "White Pigeon", county: "Saint Joseph" },
  "49101": { city: "Baroda", county: "Berrien" },
  "49102": { city: "Berrien Center", county: "Berrien" },
  "49103": { city: "Berrien Springs", county: "Berrien" },
  "49104": { city: "Berrien Springs", county: "Berrien" },
  "49106": { city: "Bridgman", county: "Berrien" },
  "49107": { city: "Buchanan", county: "Berrien" },
  "49111": { city: "Eau Claire", county: "Berrien" },
  "49112": { city: "Edwardsburg", county: "Cass" },
  "49113": { city: "Galien", county: "Berrien" },
  "49115": { city: "Harbert", county: "Berrien" },
  "49116": { city: "Lakeside", county: "Berrien" },
  "49117": { city: "New Buffalo", county: "Berrien" },
  "49119": { city: "New Troy", county: "Berrien" },
  "49120": { city: "Niles", county: "Berrien" },
  "49121": { city: "Niles", county: "Berrien" },
  "49125": { city: "Sawyer", county: "Berrien" },
  "49126": { city: "Sodus", county: "Berrien" },
  "49127": { city: "Stevensville", county: "Berrien" },
  "49128": { city: "Three Oaks", county: "Berrien" },
  "49129": { city: "Union Pier", county: "Berrien" },
  "49130": { city: "Union", county: "Cass" },
  "49201": { city: "Jackson", county: "Jackson" },
  "49202": { city: "Jackson", county: "Jackson" },
  "49203": { city: "Jackson", county: "Jackson" },
  "49204": { city: "Jackson", county: "Jackson" },
  "49220": { city: "Addison", county: "Lenawee" },
  "49221": { city: "Adrian", county: "Lenawee" },
  "49224": { city: "Albion", county: "Calhoun" },
  "49227": { city: "Allen", county: "Hillsdale" },
  "49228": { city: "Blissfield", county: "Lenawee" },
  "49229": { city: "Britton", county: "Lenawee" },
  "49230": { city: "Brooklyn", county: "Jackson" },
  "49232": { city: "Camden", county: "Hillsdale" },
  "49233": { city: "Cement City", county: "Lenawee" },
  "49234": { city: "Clarklake", county: "Jackson" },
  "49235": { city: "Clayton", county: "Lenawee" },
  "49236": { city: "Clinton", county: "Lenawee" },
  "49237": { city: "Concord", county: "Jackson" },
  "49238": { city: "Deerfield", county: "Lenawee" },
  "49239": { city: "Frontier", county: "Hillsdale" },
  "49240": { city: "Grass Lake", county: "Jackson" },
  "49241": { city: "Hanover", county: "Jackson" },
  "49242": { city: "Hillsdale", county: "Hillsdale" },
  "49245": { city: "Homer", county: "Calhoun" },
  "49246": { city: "Horton", county: "Jackson" },
  "49247": { city: "Hudson", county: "Lenawee" },
  "49248": { city: "Jasper", county: "Lenawee" },
  "49249": { city: "Jerome", county: "Hillsdale" },
  "49250": { city: "Jonesville", county: "Hillsdale" },
  "49251": { city: "Leslie", county: "Ingham" },
  "49252": { city: "Litchfield", county: "Hillsdale" },
  "49253": { city: "Manitou Beach", county: "Lenawee" },
  "49254": { city: "Michigan Center", county: "Jackson" },
  "49255": { city: "Montgomery", county: "Branch" },
  "49256": { city: "Morenci", county: "Lenawee" },
  "49257": { city: "Moscow", county: "Hillsdale" },
  "49258": { city: "Mosherville", county: "Hillsdale" },
  "49259": { city: "Munith", county: "Jackson" },
  "49261": { city: "Napoleon", county: "Jackson" },
  "49262": { city: "North Adams", county: "Hillsdale" },
  "49263": { city: "Norvell", county: "Jackson" },
  "49264": { city: "Onondaga", county: "Ingham" },
  "49265": { city: "Onsted", county: "Lenawee" },
  "49266": { city: "Osseo", county: "Hillsdale" },
  "49267": { city: "Ottawa Lake", county: "Monroe" },
  "49268": { city: "Palmyra", county: "Lenawee" },
  "49269": { city: "Parma", county: "Jackson" },
  "49270": { city: "Petersburg", county: "Monroe" },
  "49271": { city: "Pittsford", county: "Hillsdale" },
  "49272": { city: "Pleasant Lake", county: "Jackson" },
  "49274": { city: "Reading", county: "Hillsdale" },
  "49276": { city: "Riga", county: "Lenawee" },
  "49277": { city: "Rives Junction", county: "Jackson" },
  "49279": { city: "Sand Creek", county: "Lenawee" },
  "49281": { city: "Somerset", county: "Hillsdale" },
  "49282": { city: "Somerset Center", county: "Hillsdale" },
  "49283": { city: "Spring Arbor", county: "Jackson" },
  "49284": { city: "Springport", county: "Jackson" },
  "49285": { city: "Stockbridge", county: "Ingham" },
  "49286": { city: "Tecumseh", county: "Lenawee" },
  "49287": { city: "Tipton", county: "Lenawee" },
  "49288": { city: "Waldron", county: "Hillsdale" },
  "49289": { city: "Weston", county: "Lenawee" },
  "49301": { city: "Ada", county: "Kent" },
  "49302": { city: "Alto", county: "Kent" },
  "49303": { city: "Bailey", county: "Muskegon" },
  "49304": { city: "Baldwin", county: "Lake" },
  "49305": { city: "Barryton", county: "Mecosta" },
  "49306": { city: "Belmont", county: "Kent" },
  "49307": { city: "Big Rapids", county: "Mecosta" },
  "49309": { city: "Bitely", county: "Newaygo" },
  "49310": { city: "Blanchard", county: "Isabella" },
  "49311": { city: "Bradley", county: "Allegan" },
  "49312": { city: "Brohman", county: "Newaygo" },
  "49314": { city: "Burnips", county: "Allegan" },
  "49315": { city: "Byron Center", county: "Kent" },
  "49316": { city: "Caledonia", county: "Kent" },
  "49317": { city: "Cannonsburg", county: "Kent" },
  "49318": { city: "Casnovia", county: "Muskegon" },
  "49319": { city: "Cedar Springs", county: "Kent" },
  "49320": { city: "Chippewa Lake", county: "Mecosta" },
  "49321": { city: "Comstock Park", county: "Kent" },
  "49322": { city: "Coral", county: "Montcalm" },
  "49323": { city: "Dorr", county: "Allegan" },
  "49325": { city: "Freeport", county: "Barry" },
  "49326": { city: "Gowen", county: "Kent" },
  "49327": { city: "Grant", county: "Newaygo" },
  "49328": { city: "Hopkins", county: "Allegan" },
  "49329": { city: "Howard City", county: "Montcalm" },
  "49330": { city: "Kent City", county: "Kent" },
  "49331": { city: "Lowell", county: "Kent" },
  "49332": { city: "Mecosta", county: "Mecosta" },
  "49333": { city: "Middleville", county: "Barry" },
  "49335": { city: "Moline", county: "Allegan" },
  "49336": { city: "Morley", county: "Mecosta" },
  "49337": { city: "Newaygo", county: "Newaygo" },
  "49338": { city: "Paris", county: "Mecosta" },
  "49339": { city: "Pierson", county: "Montcalm" },
  "49340": { city: "Remus", county: "Mecosta" },
  "49341": { city: "Rockford", county: "Kent" },
  "49342": { city: "Rodney", county: "Mecosta" },
  "49343": { city: "Sand Lake", county: "Kent" },
  "49344": { city: "Shelbyville", county: "Allegan" },
  "49345": { city: "Sparta", county: "Kent" },
  "49346": { city: "Stanwood", county: "Mecosta" },
  "49347": { city: "Trufant", county: "Montcalm" },
  "49348": { city: "Wayland", county: "Allegan" },
  "49349": { city: "White Cloud", county: "Newaygo" },
  "49351": { city: "Rockford", county: "Kent" },
  "49355": { city: "Ada", county: "Kent" },
  "49356": { city: "Ada", county: "Kent" },
  "49357": { city: "Ada", county: "Kent" },
  "49401": { city: "Allendale", county: "Ottawa" },
  "49402": { city: "Branch", county: "Mason" },
  "49403": { city: "Conklin", county: "Ottawa" },
  "49404": { city: "Coopersville", county: "Ottawa" },
  "49405": { city: "Custer", county: "Mason" },
  "49406": { city: "Douglas", county: "Allegan" },
  "49408": { city: "Fennville", county: "Allegan" },
  "49409": { city: "Ferrysburg", county: "Ottawa" },
  "49410": { city: "Fountain", county: "Mason" },
  "49411": { city: "Free Soil", county: "Mason" },
  "49412": { city: "Fremont", county: "Newaygo" },
  "49413": { city: "Fremont", county: "Newaygo" },
  "49415": { city: "Fruitport", county: "Muskegon" },
  "49416": { city: "Glenn", county: "Allegan" },
  "49417": { city: "Grand Haven", county: "Ottawa" },
  "49418": { city: "Grandville", county: "Kent" },
  "49419": { city: "Hamilton", county: "Allegan" },
  "49420": { city: "Hart", county: "Oceana" },
  "49421": { city: "Hesperia", county: "Oceana" },
  "49422": { city: "Holland", county: "Ottawa" },
  "49423": { city: "Holland", county: "Ottawa" },
  "49424": { city: "Holland", county: "Ottawa" },
  "49425": { city: "Holton", county: "Muskegon" },
  "49426": { city: "Hudsonville", county: "Ottawa" },
  "49427": { city: "Jamestown", county: "Ottawa" },
  "49428": { city: "Jenison", county: "Ottawa" },
  "49429": { city: "Jenison", county: "Ottawa" },
  "49430": { city: "Lamont", county: "Ottawa" },
  "49431": { city: "Ludington", county: "Mason" },
  "49434": { city: "Macatawa", county: "Ottawa" },
  "49435": { city: "Marne", county: "Ottawa" },
  "49436": { city: "Mears", county: "Oceana" },
  "49437": { city: "Montague", county: "Muskegon" },
  "49440": { city: "Muskegon", county: "Muskegon" },
  "49441": { city: "Muskegon", county: "Muskegon" },
  "49442": { city: "Muskegon", county: "Muskegon" },
  "49443": { city: "Muskegon", county: "Muskegon" },
  "49444": { city: "Muskegon", county: "Muskegon" },
  "49445": { city: "Muskegon", county: "Muskegon" },
  "49446": { city: "New Era", county: "Oceana" },
  "49448": { city: "Nunica", county: "Ottawa" },
  "49449": { city: "Pentwater", county: "Oceana" },
  "49450": { city: "Pullman", county: "Allegan" },
  "49451": { city: "Ravenna", county: "Muskegon" },
  "49452": { city: "Rothbury", county: "Oceana" },
  "49453": { city: "Saugatuck", county: "Allegan" },
  "49454": { city: "Scottville", county: "Mason" },
  "49455": { city: "Shelby", county: "Oceana" },
  "49456": { city: "Spring Lake", county: "Ottawa" },
  "49457": { city: "Twin Lake", county: "Muskegon" },
  "49458": { city: "Walhalla", county: "Mason" },
  "49459": { city: "Walkerville", county: "Oceana" },
  "49460": { city: "West Olive", county: "Ottawa" },
  "49461": { city: "Whitehall", county: "Muskegon" },
  "49463": { city: "Wabaningo", county: "Muskegon" },
  "49464": { city: "Zeeland", county: "Ottawa" },
  "49468": { city: "Grandville", county: "Kent" },
  "49501": { city: "Grand Rapids", county: "Kent" },
  "49502": { city: "Grand Rapids", county: "Kent" },
  "49503": { city: "Grand Rapids", county: "Kent" },
  "49504": { city: "Grand Rapids", county: "Kent" },
  "49505": { city: "Grand Rapids", county: "Kent" },
  "49506": { city: "Grand Rapids", county: "Kent" },
  "49507": { city: "Grand Rapids", county: "Kent" },
  "49508": { city: "Grand Rapids", county: "Kent" },
  "49509": { city: "Wyoming", county: "Kent" },
  "49510": { city: "Grand Rapids", county: "Kent" },
  "49512": { city: "Grand Rapids", county: "Kent" },
  "49514": { city: "Grand Rapids", county: "Kent" },
  "49515": { city: "Grand Rapids", county: "Kent" },
  "49516": { city: "Grand Rapids", county: "Kent" },
  "49518": { city: "Grand Rapids", county: "Kent" },
  "49519": { city: "Wyoming", county: "Kent" },
  "49523": { city: "Grand Rapids", county: "Kent" },
  "49525": { city: "Grand Rapids", county: "Kent" },
  "49528": { city: "Grand Rapids", county: "Kent" },
  "49530": { city: "Grand Rapids", county: "Kent" },
  "49534": { city: "Grand Rapids", county: "Kent" },
  "49544": { city: "Grand Rapids", county: "Kent" },
  "49546": { city: "Grand Rapids", county: "Kent" },
  "49548": { city: "Grand Rapids", county: "Kent" },
  "49550": { city: "Grand Rapids", county: "Kent" },
  "49555": { city: "Grand Rapids", county: "Kent" },
  "49560": { city: "Grand Rapids", county: "Kent" },
  "49588": { city: "Grand Rapids", county: "Kent" },
  "49599": { city: "Grand Rapids", county: "Kent" },
  "49601": { city: "Cadillac", county: "Wexford" },
  "49610": { city: "Acme", county: "Grand Traverse" },
  "49611": { city: "Alba", county: "Antrim" },
  "49612": { city: "Alden", county: "Antrim" },
  "49613": { city: "Arcadia", county: "Manistee" },
  "49614": { city: "Bear Lake", county: "Manistee" },
  "49615": { city: "Bellaire", county: "Antrim" },
  "49616": { city: "Benzonia", county: "Benzie" },
  "49617": { city: "Beulah", county: "Benzie" },
  "49618": { city: "Boon", county: "Wexford" },
  "49619": { city: "Brethren", county: "Manistee" },
  "49620": { city: "Buckley", county: "Wexford" },
  "49621": { city: "Cedar", county: "Leelanau" },
  "49622": { city: "Central Lake", county: "Antrim" },
  "49623": { city: "Chase", county: "Lake" },
  "49625": { city: "Copemish", county: "Manistee" },
  "49626": { city: "Eastlake", county: "Manistee" },
  "49627": { city: "Eastport", county: "Antrim" },
  "49628": { city: "Elberta", county: "Benzie" },
  "49629": { city: "Elk Rapids", county: "Antrim" },
  "49630": { city: "Empire", county: "Leelanau" },
  "49631": { city: "Evart", county: "Osceola" },
  "49632": { city: "Falmouth", county: "Missaukee" },
  "49633": { city: "Fife Lake", county: "Kalkaska" },
  "49634": { city: "Filer City", county: "Manistee" },
  "49635": { city: "Frankfort", county: "Benzie" },
  "49636": { city: "Glen Arbor", county: "Leelanau" },
  "49637": { city: "Grawn", county: "Grand Traverse" },
  "49638": { city: "Harrietta", county: "Wexford" },
  "49639": { city: "Hersey", county: "Osceola" },
  "49640": { city: "Honor", county: "Benzie" },
  "49642": { city: "Idlewild", county: "Lake" },
  "49643": { city: "Interlochen", county: "Grand Traverse" },
  "49644": { city: "Irons", county: "Lake" },
  "49645": { city: "Kaleva", county: "Manistee" },
  "49646": { city: "Kalkaska", county: "Kalkaska" },
  "49648": { city: "Kewadin", county: "Antrim" },
  "49649": { city: "Kingsley", county: "Grand Traverse" },
  "49650": { city: "Lake Ann", county: "Benzie" },
  "49651": { city: "Lake City", county: "Missaukee" },
  "49653": { city: "Lake Leelanau", county: "Leelanau" },
  "49654": { city: "Leland", county: "Leelanau" },
  "49655": { city: "Leroy", county: "Osceola" },
  "49656": { city: "Luther", county: "Lake" },
  "49657": { city: "Mc Bain", county: "Missaukee" },
  "49659": { city: "Mancelona", county: "Antrim" },
  "49660": { city: "Manistee", county: "Manistee" },
  "49663": { city: "Manton", county: "Wexford" },
  "49664": { city: "Maple City", county: "Leelanau" },
  "49665": { city: "Marion", county: "Osceola" },
  "49666": { city: "Mayfield", county: "Grand Traverse" },
  "49667": { city: "Merritt", county: "Missaukee" },
  "49668": { city: "Mesick", county: "Wexford" },
  "49670": { city: "Northport", county: "Leelanau" },
  "49673": { city: "Old Mission", county: "Grand Traverse" },
  "49674": { city: "Omena", county: "Leelanau" },
  "49675": { city: "Onekama", county: "Manistee" },
  "49676": { city: "Rapid City", county: "Kalkaska" },
  "49677": { city: "Reed City", county: "Osceola" },
  "49679": { city: "Sears", county: "Osceola" },
  "49680": { city: "South Boardman", county: "Kalkaska" },
  "49682": { city: "Suttons Bay", county: "Leelanau" },
  "49683": { city: "Thompsonville", county: "Benzie" },
  "49684": { city: "Traverse City", county: "Grand Traverse" },
  "49685": { city: "Traverse City", county: "Grand Traverse" },
  "49686": { city: "Traverse City", county: "Grand Traverse" },
  "49688": { city: "Tustin", county: "Osceola" },
  "49689": { city: "Wellston", county: "Manistee" },
  "49690": { city: "Williamsburg", county: "Grand Traverse" },
  "49696": { city: "Traverse City", county: "Grand Traverse" },
  "49701": { city: "Mackinaw City", county: "Cheboygan" },
  "49705": { city: "Afton", county: "Cheboygan" },
  "49706": { city: "Alanson", county: "Emmet" },
  "49707": { city: "Alpena", county: "Alpena" },
  "49709": { city: "Atlanta", county: "Montmorency" },
  "49710": { city: "Barbeau", county: "Chippewa" },
  "49711": { city: "Bay Shore", county: "Charlevoix" },
  "49712": { city: "Boyne City", county: "Charlevoix" },
  "49713": { city: "Boyne Falls", county: "Charlevoix" },
  "49715": { city: "Brimley", county: "Chippewa" },
  "49716": { city: "Brutus", county: "Emmet" },
  "49717": { city: "Burt Lake", county: "Cheboygan" },
  "49718": { city: "Carp Lake", county: "Emmet" },
  "49719": { city: "Cedarville", county: "Mackinac" },
  "49720": { city: "Charlevoix", county: "Charlevoix" },
  "49721": { city: "Cheboygan", county: "Cheboygan" },
  "49722": { city: "Conway", county: "Emmet" },
  "49723": { city: "Cross Village", county: "Emmet" },
  "49724": { city: "Dafter", county: "Chippewa" },
  "49725": { city: "De Tour Village", county: "Chippewa" },
  "49726": { city: "Drummond Island", county: "Chippewa" },
  "49727": { city: "East Jordan", county: "Charlevoix" },
  "49728": { city: "Eckerman", county: "Chippewa" },
  "49729": { city: "Ellsworth", county: "Antrim" },
  "49730": { city: "Elmira", county: "Otsego" },
  "49733": { city: "Frederic", county: "Crawford" },
  "49734": { city: "Gaylord", county: "Otsego" },
  "49735": { city: "Gaylord", county: "Otsego" },
  "49736": { city: "Goetzville", county: "Chippewa" },
  "49737": { city: "Good Hart", county: "Emmet" },
  "49738": { city: "Grayling", county: "Crawford" },
  "49739": { city: "Grayling", county: "Crawford" },
  "49740": { city: "Harbor Springs", county: "Emmet" },
  "49743": { city: "Hawks", county: "Presque Isle" },
  "49744": { city: "Herron", county: "Alpena" },
  "49745": { city: "Hessel", county: "Mackinac" },
  "49746": { city: "Hillman", county: "Montmorency" },
  "49747": { city: "Hubbard Lake", county: "Alpena" },
  "49748": { city: "Hulbert", county: "Chippewa" },
  "49749": { city: "Indian River", county: "Cheboygan" },
  "49751": { city: "Johannesburg", county: "Otsego" },
  "49752": { city: "Kinross", county: "Chippewa" },
  "49753": { city: "Lachine", county: "Alpena" },
  "49755": { city: "Levering", county: "Emmet" },
  "49756": { city: "Lewiston", county: "Montmorency" },
  "49757": { city: "Mackinac Island", county: "Mackinac" },
  "49759": { city: "Millersburg", county: "Presque Isle" },
  "49760": { city: "Moran", county: "Mackinac" },
  "49761": { city: "Mullett Lake", county: "Cheboygan" },
  "49762": { city: "Naubinway", county: "Mackinac" },
  "49764": { city: "Oden", county: "Emmet" },
  "49765": { city: "Onaway", county: "Presque Isle" },
  "49766": { city: "Ossineke", county: "Alpena" },
  "49768": { city: "Paradise", county: "Chippewa" },
  "49769": { city: "Pellston", county: "Emmet" },
  "49770": { city: "Petoskey", county: "Emmet" },
  "49774": { city: "Pickford", county: "Chippewa" },
  "49775": { city: "Pointe Aux Pins", county: "Mackinac" },
  "49776": { city: "Posen", county: "Presque Isle" },
  "49777": { city: "Presque Isle", county: "Presque Isle" },
  "49779": { city: "Rogers City", county: "Presque Isle" },
  "49780": { city: "Rudyard", county: "Chippewa" },
  "49781": { city: "Saint Ignace", county: "Mackinac" },
  "49782": { city: "Beaver Island", county: "Charlevoix" },
  "49783": { city: "Sault Sainte Marie", county: "Chippewa" },
  "49784": { city: "Kincheloe", county: "Chippewa" },
  "49785": { city: "Kincheloe", county: "Chippewa" },
  "49786": { city: "Kincheloe", county: "Chippewa" },
  "49788": { city: "Kincheloe", county: "Chippewa" },
  "49790": { city: "Strongs", county: "Chippewa" },
  "49791": { city: "Topinabee", county: "Cheboygan" },
  "49792": { city: "Tower", county: "Cheboygan" },
  "49793": { city: "Trout Lake", county: "Chippewa" },
  "49795": { city: "Vanderbilt", county: "Otsego" },
  "49796": { city: "Walloon Lake", county: "Charlevoix" },
  "49797": { city: "Waters", county: "Otsego" },
  "49799": { city: "Wolverine", county: "Cheboygan" },
  "49801": { city: "Iron Mountain", county: "Dickinson" },
  "49802": { city: "Kingsford", county: "Dickinson" },
  "49805": { city: "Allouez", county: "Keweenaw" },
  "49806": { city: "Au Train", county: "Alger" },
  "49807": { city: "Bark River", county: "Delta" },
  "49808": { city: "Big Bay", county: "Marquette" },
  "49812": { city: "Carney", county: "Menominee" },
  "49814": { city: "Champion", county: "Marquette" },
  "49815": { city: "Channing", county: "Dickinson" },
  "49816": { city: "Chatham", county: "Alger" },
  "49817": { city: "Cooks", county: "Schoolcraft" },
  "49818": { city: "Cornell", county: "Delta" },
  "49819": { city: "Arnold", county: "Marquette" },
  "49820": { city: "Curtis", county: "Mackinac" },
  "49821": { city: "Daggett", county: "Menominee" },
  "49822": { city: "Deerton", county: "Alger" },
  "49825": { city: "Eben Junction", county: "Alger" },
  "49826": { city: "Rumely", county: "Alger" },
  "49827": { city: "Engadine", county: "Mackinac" },
  "49829": { city: "Escanaba", county: "Delta" },
  "49831": { city: "Felch", county: "Dickinson" },
  "49833": { city: "Little Lake", county: "Marquette" },
  "49834": { city: "Foster City", county: "Dickinson" },
  "49835": { city: "Garden", county: "Delta" },
  "49836": { city: "Germfask", county: "Schoolcraft" },
  "49837": { city: "Gladstone", county: "Delta" },
  "49838": { city: "Gould City", county: "Mackinac" },
  "49839": { city: "Grand Marais", county: "Alger" },
  "49840": { city: "Gulliver", county: "Schoolcraft" },
  "49841": { city: "Gwinn", county: "Marquette" },
  "49845": { city: "Harris", county: "Menominee" },
  "49847": { city: "Hermansville", county: "Menominee" },
  "49848": { city: "Ingalls", county: "Menominee" },
  "49849": { city: "Ishpeming", county: "Marquette" },
  "49852": { city: "Loretto", county: "Dickinson" },
  "49853": { city: "Mc Millan", county: "Luce" },
  "49854": { city: "Manistique", county: "Schoolcraft" },
  "49855": { city: "Marquette", county: "Marquette" },
  "49858": { city: "Menominee", county: "Menominee" },
  "49861": { city: "Michigamme", county: "Marquette" },
  "49862": { city: "Munising", county: "Alger" },
  "49863": { city: "Nadeau", county: "Menominee" },
  "49864": { city: "Nahma", county: "Delta" },
  "49865": { city: "National Mine", county: "Marquette" },
  "49866": { city: "Negaunee", county: "Marquette" },
  "49868": { city: "Newberry", county: "Luce" },
  "49870": { city: "Norway", county: "Dickinson" },
  "49871": { city: "Palmer", county: "Marquette" },
  "49872": { city: "Perkins", county: "Delta" },
  "49873": { city: "Perronville", county: "Menominee" },
  "49874": { city: "Powers", county: "Menominee" },
  "49876": { city: "Quinnesec", county: "Dickinson" },
  "49877": { city: "Ralph", county: "Dickinson" },
  "49878": { city: "Rapid River", county: "Delta" },
  "49879": { city: "Republic", county: "Marquette" },
  "49880": { city: "Rock", county: "Delta" },
  "49881": { city: "Sagola", county: "Dickinson" },
  "49883": { city: "Seney", county: "Schoolcraft" },
  "49884": { city: "Shingleton", county: "Alger" },
  "49885": { city: "Skandia", county: "Marquette" },
  "49886": { city: "Spalding", county: "Menominee" },
  "49887": { city: "Stephenson", county: "Menominee" },
  "49891": { city: "Trenary", county: "Alger" },
  "49892": { city: "Vulcan", county: "Dickinson" },
  "49893": { city: "Wallace", county: "Menominee" },
  "49894": { city: "Wells", county: "Delta" },
  "49895": { city: "Wetmore", county: "Alger" },
  "49896": { city: "Wilson", county: "Menominee" },
  "49901": { city: "Ahmeek", county: "Keweenaw" },
  "49902": { city: "Alpha", county: "Iron" },
  "49903": { city: "Amasa", county: "Iron" },
  "49905": { city: "Atlantic Mine", county: "Houghton" },
  "49908": { city: "Baraga", county: "Baraga" },
  "49910": { city: "Bergland", county: "Ontonagon" },
  "49911": { city: "Bessemer", county: "Gogebic" },
  "49912": { city: "Bruce Crossing", county: "Ontonagon" },
  "49913": { city: "Calumet", county: "Houghton" },
  "49915": { city: "Caspian", county: "Iron" },
  "49916": { city: "Chassell", county: "Houghton" },
  "49917": { city: "Copper City", county: "Houghton" },
  "49918": { city: "Copper Harbor", county: "Keweenaw" },
  "49919": { city: "Covington", county: "Baraga" },
  "49920": { city: "Crystal Falls", county: "Iron" },
  "49921": { city: "Dodgeville", county: "Houghton" },
  "49922": { city: "Dollar Bay", county: "Houghton" },
  "49925": { city: "Ewen", county: "Ontonagon" },
  "49927": { city: "Gaastra", county: "Iron" },
  "49929": { city: "Greenland", county: "Ontonagon" },
  "49930": { city: "Hancock", county: "Houghton" },
  "49931": { city: "Houghton", county: "Houghton" },
  "49934": { city: "Hubbell", county: "Houghton" },
  "49935": { city: "Iron River", county: "Iron" },
  "49938": { city: "Ironwood", county: "Gogebic" },
  "49942": { city: "Kearsarge", county: "Houghton" },
  "49945": { city: "Lake Linden", county: "Houghton" },
  "49946": { city: "Lanse", county: "Baraga" },
  "49947": { city: "Marenisco", county: "Gogebic" },
  "49948": { city: "Mass City", county: "Ontonagon" },
  "49950": { city: "Mohawk", county: "Keweenaw" },
  "49952": { city: "Nisula", county: "Houghton" },
  "49953": { city: "Ontonagon", county: "Ontonagon" },
  "49955": { city: "Painesdale", county: "Houghton" },
  "49958": { city: "Pelkie", county: "Houghton" },
  "49959": { city: "Ramsay", county: "Gogebic" },
  "49960": { city: "Rockland", county: "Ontonagon" },
  "49961": { city: "Sidnaw", county: "Houghton" },
  "49962": { city: "Skanee", county: "Baraga" },
  "49963": { city: "South Range", county: "Houghton" },
  "49964": { city: "Stambaugh", county: "Iron" },
  "49965": { city: "Toivola", county: "Houghton" },
  "49967": { city: "Trout Creek", county: "Ontonagon" },
  "49968": { city: "Wakefield", county: "Gogebic" },
  "49969": { city: "Watersmeet", county: "Gogebic" },
  "49970": { city: "Watton", county: "Baraga" },
  "49971": { city: "White Pine", county: "Ontonagon" },
}

// Lets start with wayne county & Ferndale
export const isAllowedZipcode = zipcode => {
  if (!zipcode.match(VALID_ZIP_PATTERN)) {
    return false
  }

  //Immediately disallow zipcodes in disallowedCities *CASE_SENSITIVE
  const disallowedCities = []
  // Allow any zipcode in allowedCounties *CASE_SENSITIVE
  const allowedCounties = ["Wayne"]
  // Allow any zipcode in additionalAllowedCities *CASE_SENSITIVE
  const additionalAllowedCities = ["Ferndale", "Southgate"]

  let zipInfo = ZIP_CODE_TO_INFO[zipcode.substr(0, 5)]
  if (zipInfo) {
    if (disallowedCities.includes(zipInfo.city)) {
      return false
    } else if (allowedCounties.includes(zipInfo.county)) {
      return true
    } else if (additionalAllowedCities.includes(zipInfo.city)) {
      return true
    }
  }

  return false
}

export const getLabelForZipCode = zip => {
  if (ZIP_CODE_TO_INFO[zip] && ZIP_CODE_TO_INFO[zip].city) {
    return ZIP_CODE_TO_INFO[zip].city
  } else {
    return zip
  }
}

export const getCountyForZipCode = zip =>
  ZIP_CODE_TO_INFO[zip] ? ZIP_CODE_TO_INFO[zip].county : null
