name: Deploy to Workers staging.goodpluck.com

on:
  push:
    branches:
      - 'staging/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # In order to make gatsby incremental build works, it's necessary .cache
      # and public folder.
      - name: Gatsby Cache Folder
        uses: actions/cache@v1
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby
          restore-keys: |
            ${{ runner.os }}-cache-gatsby

      - name: Gatsby Public Folder
        uses: actions/cache@v1
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby
          restore-keys: |
            ${{ runner.os }}-public-gatsby

      - name: Install dependencies
        run: yarn install --ignore-optional  --frozen-lockfile --production

      - name: Build
        run: yarn run build:incremental
        env:
          AIRTABLE_API_KEY: ${{secrets.AIRTABLE_API_KEY}}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          GATSBY_STRIPE_API_PUBLIC_KEY: ${{secrets.GATSBY_STRIPE_API_PUBLIC_KEY}}
          GATSBY_STAGING_STRIPE_API_PUBLIC_KEY: ${{secrets.GATSBY_STAGING_STRIPE_API_PUBLIC_KEY}}
          GATSBY_STRIPE_SHIPPING_LINE_ITEM_PRICE_ID: ${{secrets.GATSBY_STRIPE_SHIPPING_LINE_ITEM_PRICE_ID}}
          CLOUDFLARE_PURGE_CACHE_API_TOKEN: ${{secrets.CLOUDFLARE_PURGE_CACHE_API_TOKEN}}
          CLOUDFLARE_ZONE_ID: ${{secrets.CLOUDFLARE_ZONE_ID}}
          GATSBY_DEPLOY_ENVIRONMENT: 'STAGING'
          GOOGLE_ANALYTICS_TRACKING_ID: ${{secrets.GOOGLE_ANALYTICS_TRACKING_ID}}

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_WORKERS_SITES }}
          environment: 'staging'
