name: Release to staging.goodpluck.com

on:
  push:
    branches:
      - 'staging/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --ignore-optional  --frozen-lockfile --production

      - name: Build
        run: yarn run build
        env:
          AIRTABLE_API_KEY: ${{secrets.AIRTABLE_API_KEY}}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          GATSBY_STRIPE_API_PUBLIC_KEY: ${{secrets.GATSBY_STRIPE_API_PUBLIC_KEY}}
          GATSBY_STAGING_STRIPE_API_PUBLIC_KEY: ${{secrets.GATSBY_STAGING_STRIPE_API_PUBLIC_KEY}}
          GATSBY_STRIPE_SHIPPING_LINE_ITEM_PRICE_ID: ${{secrets.GATSBY_STRIPE_SHIPPING_LINE_ITEM_PRICE_ID}}
          CLOUDFLARE_PURGE_CACHE_API_TOKEN: ${{secrets.CLOUDFLARE_PURGE_CACHE_API_TOKEN}}
          CLOUDFLARE_ZONE_ID: ${{secrets.CLOUDFLARE_ZONE_ID}}
          GATSBY_DEPLOY_ENVIRONMENT: 'STAGING'
          GOOGLE_ANALYTICS_TRACKING_ID: ${{secrets.GOOGLE_ANALYTICS_TRACKING_ID}}

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_WORKERS_SITES }}
          environment: 'staging'
        env:
          USER: root
