name: Deploy to Workers Staging

on:
  push:
    branches:
      - 'staging/*'
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --prod --pure-lockfile

      - name: Build
        run: yarn run build
        env:
          AIRTABLE_API_KEY: ${{secrets.AIRTABLE_API_KEY}} 
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          GATSBY_STRIPE_API_PUBLIC_KEY: ${{secrets.STAGING_GATSBY_STRIPE_API_PUBLIC_KEY}}

      - name: Install Wrangler
        run: sudo npm i @cloudflare/wrangler -g
        
      - name: config wrangler
        run: CF_API_TOKEN_WORKERS_SITES=${{ secrets.CF_API_TOKEN_WORKERS_SITES }} wrangler publish --env staging
